export const PAGE_ROUTES = {
  NOT_FOUND: "not_found",
  MAIN: "main",
  ROADMAP: "roadmap",
  HASHTOKEN: "hashtoken",
  SWAP: "swap",
  PRELAUNCH: "prelaunch",
  CROWDSALE: "crowdsale",
  EXCHANGE: "exchange",
  INFO: "info",
  START: "start",
  ORDERS: "orders",
  POOLS: "pools",
  CREATE_POOL: "create_pool",
  EDIT_POOL: "edit_pool",
  ORDER: "order",
  FAQ: "faq",
  STAKE_REF_FAQ: "stake-ref-faq",
  TEAM: "team",
  UI: "ui",
  INSTALL_PLUGIN: "install_plugin",
  WHY_WE_AWESOME: "why_we_awesome",
  LANDING_NEW: "new_landing",
  EARN: "earn",
};
